set(SHOW_EXAMPLES OFF)

function(CMAKETOOLS_PRINT msg)
    set(newline ON)
    set(prefix "--")
    set(suffix "... ")
    # if optional arguments are passed
    if (ARGN)
        foreach (arg ${ARGN})
            string(STRIP ${arg} STR)
            string(TOLOWER ${STR} STR)
            if (${STR} STREQUAL "keep")
                set(newline OFF)
            elseif (${STR} STREQUAL "nosuffix")
                set(suffix "")
            elseif (${STR} STREQUAL "noprefix")
                set(prefix "")
            elseif (${STR} STREQUAL "status" OR ${STR} STREQUAL "setting")
                set(msg_type "${BoldMagenta}[${STR}]${ColourReset}\t")
            elseif (${STR} STREQUAL "noprint")
                return()
            endif ()
        endforeach ()
    endif ()
    if (newline)
        execute_process(COMMAND ${CMAKE_COMMAND} -E echo ${prefix} ${msg_type} ${msg} ${suffix})
    else ()
        execute_process(COMMAND ${CMAKE_COMMAND} -E echo_append ${prefix} ${msg_type} ${msg} ${suffix})
    endif ()
endfunction()

# List pre-declared CMake Variables based on the documentation. mode argument is optional but you can provide
# only one argument per function call. If multiple arguments are passed then the first one is used.
# mode can be:
#                           info        (default)
#                           all         (prints all the above, not recommended for multiple calls)
# @param string: mode (optional)
function(CMAKETOOLS_LIST_VARIABLES)
    cmake_parse_arguments(CMAKETOOLS "ALL;INFO" "" "" ${ARGN})
    if (${CMAKETOOLS_ALL})
        set(CMAKETOOLS_INFO OFF)
    endif ()

    CMAKETOOLS_PRINT("Variables that Provide Information\n" status nosuffix)
    if (${CMAKETOOLS_INFO})
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME:${ColourReset} ${PROJECT_NAME}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_SOURCE_DIR:${ColourReset} ${PROJECT_SOURCE_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_BINARY_DIR:${ColourReset} ${PROJECT_BINARY_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION:${ColourReset} ${PROJECT_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION_MAJOR:${ColourReset} ${PROJECT_VERSION_MAJOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION_MINOR:${ColourReset} ${PROJECT_VERSION_MINOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION_PATCH:${ColourReset} ${PROJECT_VERSION_PATCH}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION_TWEAK:${ColourReset} ${PROJECT_VERSION_TWEAK}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_DESCRIPTION:${ColourReset} ${PROJECT_DESCRIPTION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_HOMEPAGE_URL:${ColourReset} ${PROJECT_HOMEPAGE_URL}" status nosuffix)
    elseif(${CMAKETOOLS_ALL})
        CMAKETOOLS_PRINT("${Green}CMAKE_AR:${ColourReset} ${CMAKE_AR}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_ARGC:${ColourReset} ${CMAKE_ARGC}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_ARGV0:${ColourReset} ${CMAKE_ARGV0}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_BINARY_DIR:${ColourReset} ${CMAKE_BINARY_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_BUILD_TOOL:${ColourReset} ${CMAKE_BUILD_TOOL}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CACHEFILE_DIR:${ColourReset} ${CMAKE_CACHEFILE_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CACHE_MAJOR_VERSION:${ColourReset} ${CMAKE_CACHE_MAJOR_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CACHE_MINOR_VERSION:${ColourReset} ${CMAKE_CACHE_MINOR_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CACHE_PATCH_VERSION:${ColourReset} ${CMAKE_CACHE_PATCH_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CFG_INTDIR:${ColourReset} ${CMAKE_CFG_INTDIR}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_COMMAND:${ColourReset} ${CMAKE_COMMAND}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CPACK_COMMAND:${ColourReset} ${CMAKE_CPACK_COMMAND}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_CROSSCOMPILING:${ColourReset} ${CMAKE_CROSSCOMPILING}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_CROSSCOMPILING_EMULATOR:${ColourReset} ${CMAKE_CROSSCOMPILING_EMULATOR}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_CTEST_COMMAND:${ColourReset} ${CMAKE_CTEST_COMMAND}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CURRENT_BINARY_DIR:${ColourReset} ${CMAKE_CURRENT_BINARY_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CURRENT_LIST_DIR:${ColourReset} ${CMAKE_CURRENT_LIST_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CURRENT_LIST_FILE:${ColourReset} ${CMAKE_CURRENT_LIST_FILE}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CURRENT_LIST_LINE:${ColourReset} ${CMAKE_CURRENT_LIST_LINE}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_CURRENT_SOURCE_DIR:${ColourReset} ${CMAKE_CURRENT_SOURCE_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_DIRECTORY_LABELS:${ColourReset} ${CMAKE_DIRECTORY_LABELS}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_DL_LIBS:${ColourReset} ${CMAKE_DL_LIBS}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_DOTNET_TARGET_FRAMEWORK_VERSION:${ColourReset} ${CMAKE_DOTNET_TARGET_FRAMEWORK_VERSION}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_EDIT_COMMAND:${ColourReset} ${CMAKE_EDIT_COMMAND}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_EXECUTABLE_SUFFIX:${ColourReset} ${CMAKE_EXECUTABLE_SUFFIX}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_EXTRA_GENERATOR:${ColourReset} ${CMAKE_EXTRA_GENERATOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_EXTRA_SHARED_LIBRARY_SUFFIXES:${ColourReset} ${CMAKE_EXTRA_SHARED_LIBRARY_SUFFIXES}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_FIND_PACKAGE_NAME:${ColourReset} ${CMAKE_FIND_PACKAGE_NAME}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_FIND_PACKAGE_SORT_DIRECTION:${ColourReset} ${CMAKE_FIND_PACKAGE_SORT_DIRECTION}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_FIND_PACKAGE_SORT_ORDER:${ColourReset} ${CMAKE_FIND_PACKAGE_SORT_ORDER}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_GENERATOR:${ColourReset} ${CMAKE_GENERATOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_GENERATOR_INSTANCE:${ColourReset} ${CMAKE_GENERATOR_INSTANCE}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_GENERATOR_PLATFORM:${ColourReset} ${CMAKE_GENERATOR_PLATFORM}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_GENERATOR_TOOLSET:${ColourReset} ${CMAKE_GENERATOR_TOOLSET}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_IMPORT_LIBRARY_PREFIX:${ColourReset} ${CMAKE_IMPORT_LIBRARY_PREFIX}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_IMPORT_LIBRARY_SUFFIX:${ColourReset} ${CMAKE_IMPORT_LIBRARY_SUFFIX}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_JOB_POOL_COMPILE:${ColourReset} ${CMAKE_JOB_POOL_COMPILE}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_JOB_POOL_LINK:${ColourReset} ${CMAKE_JOB_POOL_LINK}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_JOB_POOLS:${ColourReset} ${CMAKE_JOB_POOLS}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_LINK_LIBRARY_SUFFIX:${ColourReset} ${CMAKE_LINK_LIBRARY_SUFFIX}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_LINK_SEARCH_END_STATIC:${ColourReset} ${CMAKE_LINK_SEARCH_END_STATIC}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_LINK_SEARCH_START_STATIC:${ColourReset} ${CMAKE_LINK_SEARCH_START_STATIC}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_MAJOR_VERSION:${ColourReset} ${CMAKE_MAJOR_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_MAKE_PROGRAM:${ColourReset} ${CMAKE_MAKE_PROGRAM}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_MATCH_COUNT:${ColourReset} ${CMAKE_MATCH_COUNT}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_MINIMUM_REQUIRED_VERSION:${ColourReset} ${CMAKE_MINIMUM_REQUIRED_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_MINOR_VERSION:${ColourReset} ${CMAKE_MINOR_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_NETRC:${ColourReset} ${CMAKE_NETRC}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_NETRC_FILE:${ColourReset} ${CMAKE_NETRC_FILE}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_PARENT_LIST_FILE:${ColourReset} ${CMAKE_PARENT_LIST_FILE}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_PATCH_VERSION:${ColourReset} ${CMAKE_PATCH_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_PROJECT_DESCRIPTION:${ColourReset} ${CMAKE_PROJECT_DESCRIPTION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_PROJECT_HOMEPAGE_URL:${ColourReset} ${CMAKE_PROJECT_HOMEPAGE_URL}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_PROJECT_NAME:${ColourReset} ${CMAKE_PROJECT_NAME}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_PROJECT_VERSION:${ColourReset} ${CMAKE_PROJECT_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_PROJECT_VERSION_MAJOR:${ColourReset} ${CMAKE_PROJECT_VERSION_MAJOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_PROJECT_VERSION_MINOR:${ColourReset} ${CMAKE_PROJECT_VERSION_MINOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_PROJECT_VERSION_PATCH:${ColourReset} ${CMAKE_PROJECT_VERSION_PATCH}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_PROJECT_VERSION_TWEAK:${ColourReset} ${CMAKE_PROJECT_VERSION_TWEAK}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_RANLIB:${ColourReset} ${CMAKE_RANLIB}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_ROOT:${ColourReset} ${CMAKE_ROOT}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_RULE_MESSAGES:${ColourReset} ${CMAKE_RULE_MESSAGES}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_SCRIPT_MODE_FILE:${ColourReset} ${CMAKE_SCRIPT_MODE_FILE}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_SHARED_LIBRARY_PREFIX:${ColourReset} ${CMAKE_SHARED_LIBRARY_PREFIX}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_SHARED_LIBRARY_SUFFIX:${ColourReset} ${CMAKE_SHARED_LIBRARY_SUFFIX}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_SHARED_MODULE_PREFIX:${ColourReset} ${CMAKE_SHARED_MODULE_PREFIX}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_SHARED_MODULE_SUFFIX:${ColourReset} ${CMAKE_SHARED_MODULE_SUFFIX}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_SIZEOF_VOID_P:${ColourReset} ${CMAKE_SIZEOF_VOID_P}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_SKIP_INSTALL_RULES:${ColourReset} ${CMAKE_SKIP_INSTALL_RULES}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_SKIP_RPATH:${ColourReset} ${CMAKE_SKIP_RPATH}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_SOURCE_DIR:${ColourReset} ${CMAKE_SOURCE_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_STATIC_LIBRARY_PREFIX:${ColourReset} ${CMAKE_STATIC_LIBRARY_PREFIX}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_STATIC_LIBRARY_SUFFIX:${ColourReset} ${CMAKE_STATIC_LIBRARY_SUFFIX}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_TOOLCHAIN_FILE:${ColourReset} ${CMAKE_TOOLCHAIN_FILE}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_TWEAK_VERSION:${ColourReset} ${CMAKE_TWEAK_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_VERBOSE_MAKEFILE:${ColourReset} ${CMAKE_VERBOSE_MAKEFILE}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_VERSION:${ColourReset} ${CMAKE_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_VS_DEVENV_COMMAND:${ColourReset} ${CMAKE_VS_DEVENV_COMMAND}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_VS_MSBUILD_COMMAND:${ColourReset} ${CMAKE_VS_MSBUILD_COMMAND}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}CMAKE_VS_NsightTegra_VERSION:${ColourReset} ${CMAKE_VS_NsightTegra_VERSION}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_VS_PLATFORM_NAME:${ColourReset} ${CMAKE_VS_PLATFORM_NAME}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_VS_PLATFORM_TOOLSET:${ColourReset} ${CMAKE_VS_PLATFORM_TOOLSET}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_VS_PLATFORM_TOOLSET_CUDA:${ColourReset} ${CMAKE_VS_PLATFORM_TOOLSET_CUDA}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE:${ColourReset} ${CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_VS_PLATFORM_TOOLSET_VERSION:${ColourReset} ${CMAKE_VS_PLATFORM_TOOLSET_VERSION}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION:${ColourReset} ${CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_XCODE_GENERATE_SCHEME:${ColourReset} ${CMAKE_XCODE_GENERATE_SCHEME}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}CMAKE_XCODE_PLATFORM_TOOLSET:${ColourReset} ${CMAKE_XCODE_PLATFORM_TOOLSET}" status nosuffix noprint)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME_BINARY_DIR:${ColourReset} ${${PROJECT_NAME}_BINARY_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME_DESCRIPTION:${ColourReset} ${${PROJECT_NAME}_DESCRIPTION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME_HOMEPAGE_URL:${ColourReset} ${${PROJECT_NAME}_HOMEPAGE_URL}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME_SOURCE_DIR:${ColourReset} ${${PROJECT_NAME}_SOURCE_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME_VERSION:${ColourReset} ${${PROJECT_NAME}_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME_VERSION_MAJOR:${ColourReset} ${${PROJECT_NAME}_VERSION_MAJOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME_VERSION_MINOR:${ColourReset} ${${PROJECT_NAME}_VERSION_MINOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME_VERSION_PATCH:${ColourReset} ${${PROJECT_NAME}_VERSION_PATCH}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME_VERSION_TWEAK:${ColourReset} ${${PROJECT_NAME}_VERSION_TWEAK}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_BINARY_DIR:${ColourReset} ${PROJECT_BINARY_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_DESCRIPTION:${ColourReset} ${PROJECT_DESCRIPTION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_HOMEPAGE_URL:${ColourReset} ${PROJECT_HOMEPAGE_URL}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_NAME:${ColourReset} ${PROJECT_NAME}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_SOURCE_DIR:${ColourReset} ${PROJECT_SOURCE_DIR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION:${ColourReset} ${PROJECT_VERSION}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION_MAJOR:${ColourReset} ${PROJECT_VERSION_MAJOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION_MINOR:${ColourReset} ${PROJECT_VERSION_MINOR}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION_PATCH:${ColourReset} ${PROJECT_VERSION_PATCH}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}PROJECT_VERSION_TWEAK:${ColourReset} ${PROJECT_VERSION_TWEAK}" status nosuffix)
    endif ()
    CMAKETOOLS_PRINT("\n" noprefix nosuffix)

endfunction()

# configurations for colored terminal
if (NOT WIN32 AND CMAKE_COLOR_MAKEFILE)
    string(ASCII 27 Esc)
    set(ColourReset "${Esc}[m")
    set(ColourBold "${Esc}[1m")
    set(Red "${Esc}[31m")
    set(Green "${Esc}[32m")
    set(Yellow "${Esc}[33m")
    set(Blue "${Esc}[34m")
    set(Magenta "${Esc}[35m")
    set(Cyan "${Esc}[36m")
    set(White "${Esc}[37m")
    set(BoldRed "${Esc}[1;31m")
    set(BoldGreen "${Esc}[1;32m")
    set(BoldYellow "${Esc}[1;33m")
    set(BoldBlue "${Esc}[1;34m")
    set(BoldMagenta "${Esc}[1;35m")
    set(BoldCyan "${Esc}[1;36m")
    set(BoldWhite "${Esc}[1;37m")

    if (SHOW_EXAMPLES)
        CMAKETOOLS_PRINT("This is normal" status nosuffix)
        CMAKETOOLS_PRINT("${Red}This is Red${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${Green}This is Green${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${Yellow}This is Yellow${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${Blue}This is Blue${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${Magenta}This is Magenta${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${Cyan}This is Cyan${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${White}This is White${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${BoldRed}This is BoldRed${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${BoldGreen}This is BoldGreen${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${BoldYellow}This is BoldYellow${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${BoldBlue}This is BoldBlue${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${BoldMagenta}This is BoldMagenta${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${BoldCyan}This is BoldCyan${ColourReset}" status nosuffix)
        CMAKETOOLS_PRINT("${BoldWhite}This is BoldWhite${ColourReset}\n" status nosuffix)
    endif ()

endif ()